# Theses settings a usually customize by profile

roxana:
    business:
        # Defines if no BusinessException like Null Pointer Exception, will be suppressed by a Intern Error user's friendly message.
         
        # It is useful when you want to hide not expected exception in production environment, 
        # in orther hands, you can allow the developer see the stacktrace more easily in development environment. 
        # The default value is "true".
        exception-handler:
            suppress-others-exceptions: false
            
    message-bundle:
    
        # Defines if when the application fail to translate a message, 
        # it will raise an exception or assume the pattern "???{messageKey}???" as translation.
        
        # This is usefull when you want to avoid to compromise operations in production enviroment 
        # just because the programer forgot to add a simple key in the i18n files. 
        # In the development enviroment, the programer will notice missing keys more easily if the application rises exceptions.
        # The default value is "true".
        suppress-fail-to-translate-exception: false