spring:
    application:
        name: the-amazing-book-store
    profiles:
        active: dev
    jackson:
        serialization.write_dates_as_timestamps: false
    cache:
        type: none
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:h2:file:~/h2/testdb
        username: sa
        password: 
        driver-class-name: org.h2.Driver
    jpa:
        database-platform: br.com.rooting.roxana.demo.config.H2DialectCustom
        database: H2
        open-in-view: false
        show-sql: true
        hibernate:
            ddl-auto: auto
#            naming:
#                physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
#                implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        properties:
            hibernate.id.new_generator_mappings: true
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
            hibernate.hbm2ddl.auto: validate
            
    h2:
        console:
            enabled: true
            path: /h2
        
springfox:
    documentation:
        swagger:
            v2:
                path: /docs.json
                
# Configurações gerais do Rooting Roxana.     
roxana:
    business:
        # Define o tipo do objeto retorna nas respostas do Roxana.
        response-estrategy: INTERNATIONALIZED
        
    # Define o Local e a linguagem default do Bundle de tradução utilizado pelo Roxana.
    message-bundle:
        path: locale/messages
        locale: en-US
