# Configurações gerais do Rooting Roxana.     
roxana:
    business:
        # Define o tipo do objeto retorna nas respostas do Roxana.
        response-estrategy: INTERNATIONALIZED
        
    # Define o Local e a linguagem default do Bundle de tradução utilizado pelo Roxana.
    message-bundle:
        path: locale/messages
        locale: en-US